---
deployment:
  tasks:
    - export DEPLOYPATH=/home/f296809/public_html/
    - /bin/cp index.php $DEPLOYPATH

    - /bin/cp -r src $DEPLOYPATH
    - /bin/cp -r dist $DEPLOYPATH
    - /bin/cp -r build $DEPLOYPATH
